### ISSUE TITLE
Release with credentials included

### ISSUE THREAD

**Issue by tomasfse** [liyuntao/kong-init#15]
Hello,

Could you make a release with the credentials feature included? (https://github.com/liyuntao/kong-init/commit/a1d222d9c9bdfcf4572e579fbba58d464a971380)

Thanks!

**Comment by liyuntao** [comment]
@protheantom  have a try on [v0.8.0-rc-3](https://github.com/liyuntao/kong-init/releases/tag/v0.8.0-rc-3)

also backport the credentials  feature to older version.

**Comment by tomasfse** [comment]
Thanks!

Credentials are there, now I have to be able to use them :D
